language: ruby
cache: bundler
sudo: false
rvm:
 - 2.2
before_install: 
  - rm -rf .bundle/
  - rm -rf vendor/cache/
  - rm -rf Gemfile.lock
before_script: bundle update
#script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: never